image: docker:latest
services:
  - docker:dind

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH != "main" && $CI_PIPELINE_SOURCE != "merge_request_event"      
      when: never
    - when: always

variables:
  IMAGE_NAME: $GO_BLUE_PIPELINE
  SPACE_TOKEN: $GO_BLUE_SPACE_TOKEN
  VERSION: 23

stages:          # List of stages for jobs, and their order of execution
  - compile
  - test
  - build
  - deploy

goblue-compile:       # This job runs in the build stage, which runs first.
  image: golang:latest
  stage: compile
  script:
    - go build main.go
  artifacts:
    paths:
      - main
    expire_in: 20 minutes

goblue-test:       # This job runs in the test stage, which runs first.
  stage: test
  needs:
    - goblue-compile
  script:
    - apk add git
    - apk add go
    - go build main.go
    - chmod +x main
    - ./main run >> applog.log & 
    - apk add nodejs npm
    - npm install npm@latest
    - npm i -g newman
    - npm i -g newman-reporter-junitfullreport
    - npm install -g newman-reporter-htmlextra
    - echo "Running unit tests... This will take about few minutes"
    - newman run blue_test.json -e test_env.json --env-var url=$HOSTNAME:5500 -r htmlextra --reporter-htmlextra-export  htmlreport/result.html
    - newman run blue_test.json -e test_env.json --env-var url=$HOSTNAME:5500 -r junit --reporter-junit-export junitreport/result.xml
  artifacts:
    when: always
    paths:
      - $CI_PROJECT_DIR/junitreport/*.xml
      - $CI_PROJECT_DIR/htmlreport/*.html
    reports:
      junit: $CI_PROJECT_DIR/juinitreport/*.xml
    expire_in: 20 minutes
goblue-build :       # This job runs in the build stage, which runs first.
  stage: build
  needs:
    - goblue-compile
    - goblue-test
  dependencies:
    - goblue-compile
  script:
    - docker build -t $IMAGE_NAME-$VERSION . -f goblue.Dockerfile


deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  environment: development
  script:
    - echo "Deploying application..."
    - apk add curl
    - curl -fsSL https://deta.space/assets/space-cli.sh | sh
    - space login -t $SPACE_TOKEN
    - space push 