global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: "gobluefiber"
rule_files:
scrape_configs:
  - job_name: "gobluefiber"
    static_configs:
    - targets: ['blue-admin:5500']