global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: "promethues"
rule_files:
scrape_configs:
  - job_name: "*"
    static_configs:
      - targets: ["haproxy-ingress-metrics.ingress-controller:9101"]
