apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-volume
  labels:
    type: local
    app: blueapp
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  labels:
    app: blueapp
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blueapp
  labels:
    app: blueapp-db
spec:
  selector:
    matchLabels:
      app: blueapp-db
  replicas: 1
  template:
    metadata:
      labels:
        app: blueapp-db
    spec:
      containers:
      - name: blueapp-db
        image: bluegres
        imagePullPolicy: Never
        ports:
        - containerPort: 5432
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: postgredb
      volumes:
      - name: postgredb
        persistentVolumeClaim:
          claimName: postgres-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: blueapp-database
  labels:
    app: blueapp
spec:
    selector: 
      app: blueapp-db
    type: NodePort
    ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30432
