apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blue-ingress
  annotations:
    kubernetes.io/ingress.ingressClassName: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: blue-admin.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                  name: blue-admin
                  port:
                    number: 5500