apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-back-fiber
  labels:
    app: blue-back-fiber
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blue-back-fiber
  template:
    metadata:
      labels:
        app: blue-back-fiber
    spec:
      containers:
        - name: blue-back-fiber
          image: blue-admin-v3
          imagePullPolicy: Never
          ports:
            - containerPort: 3500
          resources:
            requests:
              memory: "512Mi"
              cpu: "300m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          env:
            - name: GOMAXPROCS
              value: "4"
---
apiVersion: v1
kind: Service
metadata:
  name: blue-admin
  annotations:
    haproxy.org/check: "enabled"
    haproxy.org/forwarded-for: "enabled"
    haproxy.org/load-balance: "roundrobin"
    haproxy.org/rate-limit-requests: "1000/1s"
    prometheus.io/scrape: "true"
    prometheus.io/port: "3500"
spec:
  type: ClusterIP
  selector:
    app: blue-back-fiber
  ports:
    - protocol: TCP
      port: 3500
      targetPort: 3500
